### ISSUE TITLE
롤리팝에서는 벡터가 안돼요! ㅠㅠ

### ISSUE THREAD

**Issue by papered** [DSM-DMS/DMS-Android-V3#25]
암 쏘 새드

**Comment by jinusong** [comment]
![image](https://user-images.githubusercontent.com/37352419/55273315-e2b90500-530c-11e9-8d3d-d60375447fe4.png)

**Comment by jinusong** [comment]
물론 모든 사용자가 서비스를 누려야 한다는것이 이 서비스의 목표이지만
위 사진과 같이 DMS는 출시할 때부터 안드로이드 5.1 버전 이상만 지원한다고 명시를 했고
소수의 5.0 이하 버전 사용자의 지원불가를 해결하기 위해
모든 사용자가 png를 사용해야 될지도 모르는 불편함을 감수하기는 어렵네요.

**Comment by jinusong** [comment]
그리고 DMS 서비스가 안드로이드 앱만 있는 것이 아니라 웹도 있기 때문에
다음과 같은 사용자들은 웹을 사용하는 것이 좋겠다는 것이 제 생각입니다.

**Comment by papered** [comment]
음 저도 인정합니다
