### ISSUE TITLE
페이지 바꿀시, 페이지 재시작?

### ISSUE THREAD

**Issue by SeungYongSon** [DSM-DMS/DMS-Android-V3#26]
bottom navigation view를 통해 
다른 페이지로 넘어가면 페이지안에 있는 fragment가 재시작 되는것을 보았습니다.
재시작된다는 것은 서버에게 다시한번 더 데이터를 요청한다는 것인데
이는 유저 입장에서는 불필요한 작업이라고 생각이 들었습니다.
째든..일부러 페이지를 재시작하는 것인지 아니면
이러한 부분에 대해 생각을 하지 못한 것인지 궁금합니다.

**Comment by jinusong** [comment]
급식이나 마이페이지요?

**Comment by SeungYongSon** [comment]
네넹

**Comment by papered** [comment]
프래그먼트 재사용 시 앱 죽는 경우 있어서 일부러 유도한 것
어짜피 나중에 Navigation Component로 마이그레이션 할 것이였고, 지금 당장 크게 문제될 것 같지 않아서 아직 냅뒀음

**Comment by SeungYongSon** [comment]
ㅇㅎ

**Comment by SeungYongSon** [comment]
@PaperEd 혹시 Navigation Component 에 대한 자료나 포스팅 글 좀 공유 가능하신가요?

**Comment by papered** [comment]
https://proandroiddev.com/navigation-architecture-component-for-the-rest-of-us-faafa890e5
조와용

**Comment by SeungYongSon** [comment]
이참에 aac 랑 jetpack 도 ㅎㅎ

**Comment by papered** [comment]
어떤 자료를 보고 공부했는지 기억이 안나네요 ㅠㅜ
그냥 [Android Sunflower](https://github.com/googlesamples/android-sunflower) 보셔도 무관할듯..!

**Comment by jinusong** [comment]
ㅇㅎ

**Comment by SeungYongSon** [comment]
아앗... 알겠습니당.. 그럼 잘 읽을게요 ㅎㅎ

**Comment by SeungYongSon** [comment]
그럼 이 이슈는 닫습니당~~~
